[package]
name = "test_qt_rust"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
cxx = "1.0.92"
cxx-qt = "0.5.0"
cxx-qt-lib = "0.5.0"

[build-dependencies]
cxx-qt-build = "0.5.0"
